### ISSUE TITLE
Azure DevOps - Node 6 runtime

### ISSUE THREAD

**Issue by gerritlansing** [CycodeLabs/cimon-action#70]
Hello,

It looks like when run in Azure DevOps that the task utilizes the Node 6 runtime, which we've disabled. Could you please update to use Node 16?

<img width="1303" alt="image" src="https://github.com/CycodeLabs/cimon-action/assets/31254206/17838400-f4ee-41ff-87d6-0189ddf65591">

Thanks,
Gerrit

**Comment by alex-ilgayev** [comment]
Hey, @gerritlansing , thanks for raising this issue.
I've updated the Node runtime to 16. Let me know if that works for you.
Pay attention that the Cimon task should be at version `0.9.9`. Sometimes it takes some time for it to be updated to the latest version.

**Comment by gerritlansing** [comment]
Hi @alex-ilgayev, thanks for the quick response. Can confirm that 0.9.9 is deployed and running. Is it expected that it is no longer running as a "pre-job" task?

With 0.9.7:
<img width="283" alt="image" src="https://github.com/CycodeLabs/cimon-action/assets/31254206/08df8311-2d17-4296-938d-a06d162979fb">

With 0.9.9:
<img width="257" alt="image" src="https://github.com/CycodeLabs/cimon-action/assets/31254206/167da3c2-35e1-43ec-a754-7772f3e7ea7d">

**Comment by alex-ilgayev** [comment]
Glad it worked!
The behavior you indicated is intended. We changed the Azure task to work similarly to the Github task.
Means - previously, it didn't matter when you started the task, it would run from the start using a pre task execution.
Now (similar to Github behavior), it starts the moment you define the Cimon task to the end of the job.

**Comment by gerritlansing** [comment]
Hi @alex-ilgayev, got it, thanks for the update. I did like it running pre-task execution to be sure that all pipeline steps were caught.
